cxx_library(
    name = "Minecraft.World",
    srcs = glob(
        ["*.cpp"],
        exclude = ["ZonedChunkStorage.cpp"],
    ),
    exported_headers = glob([
        "*.h",
        "x64headers/**/*.h",
        "pch/**/*.h",
    ]),
    compiler_flags = [
        "-std=c++26",
        "-D_SDL3",
        "-DGL_GLES_PROTOTYPES",
        "-DGL_GLEXT_PROTOTYPES",
        "-include",
        "Minecraft.World/stdafx.h",
    ],
    public_include_directories = [
        ".",
        "x64headers",
    ],
    exported_deps = [
        "//Minecraft.Client:Minecraft.Client.headers",
        "third_party//mimalloc:mimalloc",
        "third_party//zlib-ng:zlib",
    ],
    visibility = ["PUBLIC"],
)
