cxx_precompiled_header(
    name = "world_pch",
    src = "stdafx.h",
    compile_pch_file = True,
    pch_clanguage = ".cpp",
    compiler_flags = [
        "-std=c++26",
        "-pedantic-errors",
        "-Wno-gnu-anonymous-struct",
        "-Wno-nested-anon-types",
        "-Wno-non-c-typedef-for-linkage",
        "-Wno-invalid-utf8",
    ],
    preprocessor_flags = [
        "-D_SDL3",
        "-D_DEBUG_MENUS_ENABLED",
        "-D_LARGE_WORLDS",
        "-DSPLIT_SAVES",
    ],
    public_include_directories = [
        ".",
        "x64headers",
        "../Minecraft.Client/SDL3",
        "../Minecraft.Client/SDL3/stubs",
    ],
    deps = [
        "//third_party:sdl3",
        "//third_party:sdl3_image",
    ],
)

cxx_library(
    name = "Minecraft.World",
    srcs = glob(["*.cpp"], exclude = ["ZonedChunkStorage.cpp"]),
    prefix_header = "stdafx.h",
    compiler_flags = [
        "-std=c++26",
        "-pedantic-errors",
        "-Wno-gnu-anonymous-struct",
        "-Wno-nested-anon-types",
        "-Wno-non-c-typedef-for-linkage",
        "-Wno-invalid-utf8",
    ],
    preprocessor_flags = [
        "-D_SDL3",
        "-D_DEBUG_MENUS_ENABLED",
        "-D_LARGE_WORLDS",
        "-DSPLIT_SAVES",
    ],
    public_include_directories = [
        ".",
        "x64headers",
        "../Minecraft.Client/SDL3",
        "../Minecraft.Client/SDL3/stubs",
    ],
    exported_deps = ["//third_party:sdl3", "//third_party:sdl3_image"],
    visibility = ["PUBLIC"],
)
