#pragma once

#include "BasicTree.h"
#include "BirchFeature.h"
#include "CactusFeature.h"
#include "CaveFeature.h"
#include "ClayFeature.h"
#include "DeadBushFeature.h"
#include "Feature.h"
#include "FlowerFeature.h"
#include "HellFireFeature.h"
#include "HellPortalFeature.h"
#include "HellSpringFeature.h"
#include "HouseFeature.h"
#include "LakeFeature.h"
#include "LightGemFeature.h"
#include "MonsterRoomFeature.h"
#include "OreFeature.h"
#include "PineFeature.h"
#include "PumpkinFeature.h"
#include "ReedsFeature.h"
#include "SpringFeature.h"
#include "SpruceFeature.h"
#include "TallGrassFeature.h"
#include "TreeFeature.h"

#include "BonusChestFeature.h"
#include "EndPodiumFeature.h"
#include "HugeMushroomFeature.h"
#include "SandFeature.h"
#include "SpikeFeature.h"
#include "SwampTreeFeature.h"

#include "DesertWellFeature.h"
#include "GroundBushFeature.h"
#include "MegaTreeFeature.h"
#include "VinesFeature.h"
